/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = 'devotion';

  static const IconData icons_dots = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_next = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_like = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_like_dark = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_share_dark = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_transport_car = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_arr = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_chevron_light = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_add = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_localization = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_rideshare = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_transport_bus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_comment_dark = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_close = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_menu = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_comment = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_share = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_setting = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_add = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_search = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_share = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_localization = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_pac = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_light_setting = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_printer = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_walking = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icond_filter_light = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_chevron = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_cross_small = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_search = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_share = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_next = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_back = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_close = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_filter = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons_dark_menu = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
